services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: empleados_app
    restart: unless-stopped
    working_dir: /var/www
    environment:
      TZ: America/Tijuana
    volumes:
      - .:/var/www
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    ports:
      - "5174:5173"
      - "8086:8080"
    depends_on:
      - db
    networks:
      - central_api_net

  web:
    image: nginx:alpine
    container_name: empleados_web
    restart: unless-stopped
    ports:
      - "9290:80"
    environment:
      TZ: America/Tijuana
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - central_api_net

  redis:
    image: redis:alpine
    container_name: empleados_redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    networks:
      - central_api_net

  db:
    image: mysql:8.0
    container_name: empleados_db
    restart: unless-stopped
    environment:
      TZ: America/Tijuana
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sistemas
      MYSQL_USER: rishar
      MYSQL_PASSWORD: secretpassword
    ports:
      - "3310:3306"
    volumes:
      - modern_dbdata:/var/lib/mysql
    networks:
      - central_api_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: empleados_pma
    restart: unless-stopped
    ports:
      - "8291:80"
    environment:
      TZ: America/Tijuana
      PMA_HOST: db
      PMA_ARBITRARY: 1
    depends_on:
      - db
    networks:
      - central_api_net

networks:
  central_api_net:
    name: central_api_net
    driver: bridge

volumes:
  modern_dbdata:
