<?php

namespace App\Constants;

class PayrollMapping
{
    public static function getMapping(): array
    {
        return [
            // Percepciones
            'sal_base' => ['code' => '01', 'name' => 'Sueldo'],
            'prev_social' => ['code' => '02', 'name' => 'Previsión social'],
            'compensacion' => ['code' => '03', 'name' => 'Compensación Garantizada'],
            'riesgo_prof' => ['code' => '04', 'name' => 'Compensación por Riesgo Profesional'],
            'comp_x_antig' => ['code' => '05', 'name' => 'Compensación por Antigüedad'],
            'quniquenio' => ['code' => '06', 'name' => 'Quinquenio'],
            'turno_opcional' => ['code' => '07', 'name' => 'Turno Opcional'],
            'percep_adic' => ['code' => '08', 'name' => 'Percepción Adicional'],
            'imp_hext_dob' => ['code' => '09', 'name' => 'Horas Extras Dobles'],
            'imp_hext_tri' => ['code' => '09', 'name' => 'Horas Extras Triples'],
            'despensa' => ['code' => '10', 'name' => 'Despensa'],
            'honorarios' => ['code' => '11', 'name' => 'Honorarios'],
            'beca_pasan_pre' => ['code' => '12', 'name' => 'Beca Pasantes'],
            'ayuda_renta_bec' => ['code' => '13', 'name' => 'Ayuda Renta Becario'],
            'p_domtrab_gr_st' => ['code' => '14', 'name' => 'Dom. Trabajado Gravable'],
            'remun_guardias' => ['code' => '15', 'name' => 'Remun. Guardias'],
            'dev_ded_indeb' => ['code' => '16', 'name' => 'Devol. Deducciones Indeb.'],
            'compensa_unica' => ['code' => '17', 'name' => 'Compensación Única'],
            'grava_vac_st' => ['code' => '18', 'name' => 'Prima Vacacional'],
            'exento_vacacion' => ['code' => '18', 'name' => 'Parte exenta Paga Vacacional'],
            'p_domtrab_ex_st' => ['code' => '14', 'name' => 'Prima Dominical Exenta'],
            'prima_dom_ex' => ['code' => '14', 'name' => 'Dom. Trabajado Exento'],
            'prima_dom_gra' => ['code' => '14', 'name' => 'Prima Dominical Gravable'],
            'beca_hijos' => ['code' => '19', 'name' => 'Becas Hijos Trab.'],
            'ayuda_lentes' => ['code' => '20', 'name' => 'Ayuda de Lentes'],
            'premio_aniver' => ['code' => '21', 'name' => 'Premio Aniversario'],
            'primo_10_mayo' => ['code' => '22', 'name' => 'Premio 10 de Mayo'],
            'premio_antig' => ['code' => '23', 'name' => 'Premio Antigüedad'],
            'estimulo_adic' => ['code' => '24', 'name' => 'Estímulo Mensual Antig.'],
            'dias_eco_no_disf' => ['code' => '24', 'name' => 'Días Económicos'],
            'servs_event' => ['code' => '25', 'name' => 'Compensación por Servicios Eventuales'],
            'paga_extra_1' => ['code' => '26', 'name' => 'Aguinaldo'],
            'premio_moneda' => ['code' => '27', 'name' => 'Moneda de Oro'],
            'est_prod_cal' => ['code' => '28', 'name' => 'Estímulo Productividad'],
            'material_didac' => ['code' => '29', 'name' => 'Material Didáctico'],
            'estimulo_pro_mm' => ['code' => '30', 'name' => 'Estímulo Desempeño MM'],
            'remun_suplencia' => ['code' => '31', 'name' => 'Remun. Suplencias'],
            'bono_reyes' => ['code' => '32', 'name' => 'Bono Día de Reyes'],
            'ayuda_transp' => ['code' => '33', 'name' => 'Ayuda Transporte'],
            'ayuda_utiles' => ['code' => '34', 'name' => 'Útiles Escolares'],
            'asigna_medico' => ['code' => '35', 'name' => 'Asignación'],
            'comple_beca_med' => ['code' => '36', 'name' => 'Complem. Beca Médicos'],
            'esti_asistencia' => ['code' => '37', 'name' => 'Estímulo Asistencia'],
            'esti_puntuali' => ['code' => '38', 'name' => 'Estímulo Puntualidad'],
            'esti_desempeno' => ['code' => '39', 'name' => 'Estímulo Desempeño'],
            'esti_merito_rel' => ['code' => '40', 'name' => 'Mérito Relevante'],
            'prem_ant_25_30' => ['code' => '41', 'name' => 'Premio Antigüedad 25/30'],
            'ayuda_muerfam' => ['code' => '42', 'name' => 'Muerte Familiar'],
            'impr_tesis' => ['code' => '43', 'name' => 'Imprensión Tesis'],
            'apoyo_desa_capa' => ['code' => '44', 'name' => 'Desarrollo y Cap.'],
           // 'exceso_credito' => ['code' => '45', 'name' => 'Pensión Alimenticia'],
            'subsidio_empleo' => ['code' => '46', 'name' => 'Subsidio Empleo'],
            'vale_dec' => ['code' => '47', 'name' => 'Valle Decembrino'],
            'ayuda_actualiza' => ['code' => '48', 'name' => 'Gastos Actualización'],
            'esti_trab_mes' => ['code' => '49', 'name' => 'Trabajador del Mes'],
            'ajuste_sueldo' => ['code' => '99', 'name' => 'Ajuste Sueldo'],
            'compen_isr_agui' => ['code' => 'AC', 'name' => 'Compensacion ISR de Aguinaldo (0CC)'],
            'apoyo_deporte' => ['code' => 'AD', 'name' => 'Apoyo Deporte'],
            'mant_vehiculo' => ['code' => 'AV', 'name' => 'Mant. Vehículo'],
            'beca_residentes' => ['code' => 'B2', 'name' => 'Becas Residentes'],
            'ajuste_residen' => ['code' => 'B3', 'name' => 'Ajuste Méd. Residentes'],
            'pago_retiro' => ['code' => 'B4', 'name' => 'Pago por Retiro Voluntario'],
            'premio_nac_anti' => ['code' => 'B5', 'name' => 'Premio Nac. Antigüedad'],
            'ajuste_calend' => ['code' => 'B7', 'name' => 'Ajuste Calendario'],
            'comision' => ['code' => 'B8', 'name' => 'Comisiones'],
            'jornada_noct' => ['code' => 'C2', 'name' => 'Jornada Nocturna'],
            'prem_est_recomp' => ['code' => 'C3', 'name' => 'Premios Estimulos y Recompensas'],
            'cobro_puest_ant' => ['code' => 'C4', 'name' => 'Cobro Puesto Ant.'],
            'prest_pago_exce' => ['code' => 'C4', 'name' => 'Préstamo Pago Exceso'],
            'guardias_provac' => ['code' => 'C5', 'name' => 'Guardias PROVAC'],
            'suplen_provac' => ['code' => 'C6', 'name' => 'Suplencias PROVAC'],
            'dev_nograv' => ['code' => 'C9', 'name' => 'Devol. No Gravables'],
            'maternid_tot_st' => ['code' => 'CM', 'name' => 'Canastilla Materna'],
            'grat_mes_beca' => ['code' => 'E2', 'name' => 'Gratif. Mes Beca'],
            'f_ahorro_ind_dv' => ['code' => 'F1', 'name' => 'Aport. Trabajador'],
            'f_ahorro_empr_dv' => ['code' => 'F2', 'name' => 'Aport. Instituto'],
            'f_ahorro_sind_dv' => ['code' => 'F3', 'name' => 'Aport. Sindicato'],
            'prevenissste' => ['code' => 'FV', 'name' => 'Prevenissste'],
            'reco_serpub' => ['code' => 'RE', 'name' => 'Reconocimiento S.P.'],
            'rezago_quir' => ['code' => 'RQ', 'name' => 'Rezago Quirúrgico'],
            'aport_pat_bruta' => ['code' => 'SS', 'name' => 'Aport. Patr. Bruta'],
            
            // Deducciones
            'insasis' => ['code' => '50', 'name' => 'Inasistencias'],
            'servicio_medico' => ['code' => '51', 'name' => 'Servicio Médico'],
            'fondo_prestaci' => ['code' => '52', 'name' => 'Fondo Prestaciones'],
            'ispt' => ['code' => '53', 'name' => 'Impuesto sobre la Renta'],
            'ispt_ext' => ['code' => '53', 'name' => 'ISPT Pagas Extras'],
            'c_sindic_local' => ['code' => '54', 'name' => 'Cuota Sindical Local'],
            'seguro_hip' => ['code' => '55', 'name' => 'Seguro Hipotecario'],
            'credito_hip' => ['code' => '56', 'name' => 'Crédito Hipotecario'],
            'seguro_hip_aval' => ['code' => '57', 'name' => 'Seg. Hip. Avalado'],
            'credito_hip_aval' => ['code' => '58', 'name' => 'Créd. Hip. Avalado'],
            'renta_multi' => ['code' => '59', 'name' => 'Renta Multifamiliar'],
            'comision_auxil' => ['code' => '61', 'name' => 'Comisión Auxilio'],
            'prest_med_plazo' => ['code' => '60', 'name' => 'Préstamo Personal'],
            'cred_fovissste' => ['code' => '62', 'name' => 'Crédito FOVISSSTE'],
            'seg_vida_hid1' => ['code' => '63', 'name' => 'Seguro Metlife (1)'],
            'seg_vida_hid2' => ['code' => '64', 'name' => 'Seguro Metlife (2)'],
            'seg_institucion' => ['code' => '65', 'name' => 'Seguro Institucional'],
            'seg_retiro' => ['code' => '66', 'name' => 'Seguro Col. Retiro'],
            'cuota_dep' => ['code' => '67', 'name' => 'Cuota Deportiva'],
            'total_p_alimen' => ['code' => '69', 'name' => 'Pensión Alimenticia'],
            'retardos' => ['code' => '70', 'name' => 'Retardos'],
            'rei_sdo_cob_ind' => ['code' => '71', 'name' => 'Reintegro Sueldo'],
            'otras_deduc' => ['code' => '72', 'name' => 'Otras Deducciones'],
            'prest_auto_sup' => ['code' => '73', 'name' => 'Préstamo Auto Sup.'],
            'seg_auto_ca' => ['code' => '75', 'name' => 'AXA Seguros'],
            'ajuste_fonac' => ['code' => '76', 'name' => 'Ajuste Fonac'],
            'f_ahorro_indi' => ['code' => '77', 'name' => 'Fondo Ahorro Cap.'],
            'prest_auto_med' => ['code' => '78', 'name' => 'Prést. Auto MM'],
            'aport_vol_sar' => ['code' => '79', 'name' => 'Aport. Vol. SAR'],
            'ahorro_solid' => ['code' => '7S', 'name' => 'Ahorro Solidario'],
            'serv_gastos_fun' => ['code' => '81', 'name' => 'Gastos Funerarios'],
            'seg_auto_nprov' => ['code' => '83', 'name' => 'Seguro Auto GNP'],
            'prest_adicional' => ['code' => '85', 'name' => 'Crédito Adicional'],
            'seg_danios_fov' => ['code' => '86', 'name' => 'Seguro Daños FOV'],
            'seg_vida_int' => ['code' => '87', 'name' => 'Seguro de Vida'],
            'cred_ahorra_ya' => ['code' => '88', 'name' => 'Crédito Ahorra-Ya'],
            'adeud_pens_alim' => ['code' => '89', 'name' => 'Adeudo Pens. Alim.'],
            'isr_ajuste_ant' => ['code' => '90', 'name' => 'Ajuste Anual ISR'],
            'recup_viaticos' => ['code' => '92', 'name' => 'Recup. Viáticos'],
            'aten_med_no_der' => ['code' => '93', 'name' => 'Aten. Médica No-D.'],
            'desc_ant_sueldo' => ['code' => '94', 'name' => 'Anticipo Sueldo'],
            'respon_dano_pat' => ['code' => '95', 'name' => 'Resp. Daño Patrim.'],
            'respon_dif_suel' => ['code' => '96', 'name' => 'Resp. Dif. Sueldo'],
            'sancion_adminis' => ['code' => '97', 'name' => 'Sanción Admin.'],
            'sancion_pecunia' => ['code' => '98', 'name' => 'Sanción Pecuniaria'],
            'isr_aguin' => ['code' => 'AI', 'name' => 'ISR Aguinaldo'],
            'aport_pat_neta' => ['code' => 'AN', 'name' => 'Aport. Patronal Neta'],
            'seg_argos' => ['code' => 'AR', 'name' => 'Seguros Argos'],
            'fonacot' => ['code' => 'CF', 'name' => 'Crédito FONACOT'],
            'credipresto' => ['code' => 'CP', 'name' => 'Credipresto'],
            'c_sindic_nacion' => ['code' => 'CS', 'name' => 'Sind. Independiente'],
            'desc_pago_exces' => ['code' => 'D1', 'name' => 'Desc. Pago Exceso'],
            'exceso_licencias' => ['code' => 'D2', 'name' => 'Exceso Lic. Médicas'],
            'desc_optica' => ['code' => 'D3', 'name' => 'Descuento Optica'],
            'seg_vida_fam' => ['code' => 'D5', 'name' => 'Resp. Civil y Prof.'],
            'credito_etesa' => ['code' => 'ET', 'name' => 'Crédito ETESA'],
            'fimubac' => ['code' => 'FB', 'name' => 'Fimubac'],
            'gasmedmay' => ['code' => 'GM', 'name' => 'Seg. Gastos Médicos'],
            'ispt_mant_vehi' => ['code' => 'ID', 'name' => 'Impuesto Vehículo'],
            'isr_patronal_ss' => ['code' => 'IS', 'name' => 'ISR Patronal SS'],
            'gastos_funer' => ['code' => 'PP', 'name' => 'Previsora Plenitud'],
            'nuevo_fovissste' => ['code' => 'NF', 'name' => 'Nuevo FOVISSSTE'],
            'presta_auto_fun' => ['code' => 'PF', 'name' => 'Prést. Funcionarios'],
            //'prevision_flex' => ['code' => 'PP', 'name' => 'Previsora Plenitud'],
            'prestamo_ssi' => ['code' => 'PS', 'name' => 'Préstamo sobre SSI'],
            'publiseg' => ['code' => 'PU', 'name' => 'Publiseg'],
            'seg_qualitas' => ['code' => 'QA', 'name' => 'Qualitas'],
            'amort_fonacot' => ['code' => 'RF', 'name' => 'Reestruc. Financiera'],
            'reten_judicial' => ['code' => 'RM', 'name' => 'Retención Judicial'],
            'seguro_salud' => ['code' => 'S7', 'name' => 'Seguro de Salud'],
            'seguro_ries_trab' => ['code' => 'S8', 'name' => 'Riesgos de Trabajo'],
            'seguro_inval_y_vida' => ['code' => 'S9', 'name' => 'Seguro Invalidez y Vida'],
            'sindicato_tres' => ['code' => 'SA', 'name' => 'Sindicato SNADETISSSTE'],
            'sindicato_cuatro' => ['code' => 'SD', 'name' => 'Sindicato SINADTEISSSTE'],
            'sindicato_cinco' => ['code' => 'SD', 'name' => 'Sindicato 5'],
            'seguro_hip_2' => ['code' => 'SH', 'name' => 'Seguro Hipotecario'],
            'seguro_separac' => ['code' => 'SI', 'name' => 'Seguro Separación'],
            'sindicato_suts' => ['code' => 'SN', 'name' => 'Sindicato SUTS'],
            'seg_resp_civil' => ['code' => 'SR', 'name' => 'Resp. Civil'],
            'concepto_nuevo_03' => ['code' => 'ST', 'name' => 'Sindicato SINAPTISSSTE'],
            'concepto_nuevo_02' => ['code' => 'SU', 'name' => 'Sindicato SUTISSSTE'],
            'seguro_cesantia' => ['code' => '4S', 'name' => 'Seguro Cesantia'],
            'serv_soc_y_cult' => ['code' => '1S', 'name' => 'Servicios Soc. y Culturales'],
            'anticipo' => ['code' => 'D5', 'name' => 'Seguro de Resp. Civil y Prof.'],
        ];
    }
}
